const SQUARE_CLICKED = 'SQUARE_CLICKED';
const GET_BOARD_SIZE = 'GET_BOARD_SIZE';
const BOARD_CREATED = 'BOARD_CREATED';
const INITIAL_STATE = 'INITIAL_STATE';
const CHECK_PLAY_COUNT = 'CHECK_PLAY_COUNT';
const CHECK_WIN = 'CHECK_WIN';
const X_WINNER = 'X_WINNER';
const O_WINNER = 'O_WINNER';
const CATS_GAME = 'CATS_GAME';

export default { BOARD_CREATED, SQUARE_CLICKED, GET_BOARD_SIZE, CHECK_PLAY_COUNT, CHECK_WIN, X_WINNER, O_WINNER, CATS_GAME };