const SQUARE_CLICKED = 'SQUARE_CLICKED';
const GET_BOARD_SIZE = 'GET_BOARD_SIZE';
const BOARD_CREATED = 'BOARD_CREATED';
const INITIAL_STATE = 'INITIAL_STATE';

export default { BOARD_CREATED, SQUARE_CLICKED, GET_BOARD_SIZE };